services:
    pnz.messenger.filesystem_transport.factory:
        class: 'Pnz\Messenger\FilesystemTransport\FilesystemTransportFactory'
        arguments:
            $serializer: '@messenger.transport.serializer'
            $filesystem: '@filesystem'
            $lockFactory: '@lock.factory'
        tags: ['messenger.transport_factory']
