services:
    pnz.messenger.filesystem_transport.factory:
        class: 'Pnz\Messenger\FilesystemTransport\FilesystemTransportFactory'
        arguments:
            $encoder: '@messenger.transport.encoder'
            $decoder: '@messenger.transport.decoder'
            $filesystem: '@filesystem'
            $lockFactory: '@lock.factory'
        tags: ['messenger.transport_factory']
